train_csv: /media/data2/vv/dvc_datasets/dataset_ppe/ppe_multilabel_crops_a34ad4f6bed4dde55efde4acbea618cf1526eb24/ann/train.csv
val_csv: /media/data2/vv/dvc_datasets/dataset_ppe/ppe_multilabel_crops_a34ad4f6bed4dde55efde4acbea618cf1526eb24/ann/val.csv
images: /media/data2/vv/dvc_datasets/dataset_ppe/ppe_multilabel_crops_a34ad4f6bed4dde55efde4acbea618cf1526eb24/crops/

height: 185
width: 80

labels:
    harness:
        - in_harness
        - not_in_harness
        - harness_unrecognized
    vest:
        - in_vest
        - not_in_vest
        - vest_unrecognized
    hardhat:
        - in_hardhat
        - not_in_hardhat
        - hardhat_unrecognized
    person_in_bucket:
        - person_in_bucket
        - person_not_in_bucket

labels_to_get_averaged_metrics: [0,1,3,4,6,7,9,10]

nc: 11

class_weights:
    hardhat:
        in_hardhat: 0.01
        not_in_hardhat: 0.99
        hardhat_unrecognized: 0.005
    vest:
        in_vest: 0.4
        not_in_vest: 0.6
        vest_unrecognized: 0.01
    harness:
        in_harness: 0.99
        not_in_harness: 0.01
        harness_unrecognized: 0.03

