train_annot: '/media/data2/vv/dvc_datasets/dataset_ppe/for_experiments/seah_hardhat_coco/ann/hardhat/train.json'
val_annot: '/media/data2/vv/dvc_datasets/dataset_ppe/for_experiments/seah_hardhat_coco/ann/hardhat/val.json'
images: '/media/data2/vv/dvc_datasets/dataset_ppe/for_experiments/seah_hardhat_coco/images/'

label_names: ['in_hardhat','not_in_hardhat','hardhat_unrecognized']

height: 736
width: 1080